### ISSUE TITLE
Workflow input processing failed

### ISSUE THREAD

**Issue by kmosi0** [Cristianetaniguti/Reads2Map#104]
I try the  EmpiricalSNPCalling pipeline using Pumbaa with example files in WSL in Windows 10. I follow the steps on the guide page. But I get the error "Workflow input processing failed".  
 ../bin/pumbaa metadata -o  00461381-62e3-418c-885e-d1d0845acfc7
2023/07/08 23:52:40 GET request to: http://127.0.0.1:8000/api/workflows/v1/00461381-62e3-418c-885e-d1d0845acfc7/metadata?excludeKey=executionEvents&excludeKey=jes&excludeKey=inputs
+------+---------+---------+--------+
| TASK | ATTEMPT | ELAPSED | STATUS |
+------+---------+---------+--------+
+------+---------+---------+--------+
❗You have 1 issue:
 - Workflow input processing failed

I check the path and files are correct, when I run "java -jar ~/.cromwell/cromwell.jar run  EmpiricalSNPCalling_develop/EmpiricalSNPCalling_develop.wdl -i test.json." it would not note input error info. hope for your help.

**Comment by kmosi0** [comment]
input json file 
{
"SNPCalling.max_cores": 2,
"SNPCalling.pair_end": false,
"SNPCalling.enzyme": "HindIII",
"SNPCalling.max_ram": 2000,
"SNPCalling.ploidy": 2,
"SNPCalling.rm_dupli": false,
"SNPCalling.run_gatk": true,
"SNPCalling.run_freebayes": false,
"SNPCalling.run_tassel": true,
"SNPCalling.run_stacks": false,
"SNPCalling.hardfilters": true,
"SNPCalling.n_chrom": 1,
"SNPCalling.chunk_size": 1,
"SNPCalling.samples_info": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/samples_info_pop_sub.tsv",
"SNPCalling.references": {
"ref_fasta": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/Chr10.11.2M.fa",
"ref_dict": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/Chr10.11.2M.dict",
"ref_ann": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/Chr10.11.2M.fa.ann",
"ref_sa": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/Chr10.11.2M.fa.sa",
"ref_amb": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/Chr10.11.2M.fa.amb",
"ref_pac": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/Chr10.11.2M.fa.pac",
"ref_bwt": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/Chr10.11.2M.fa.bwt",
"ref_fasta_index": "/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/Chr10.11.2M.fa.fai"
}
}

samples_info_pop_sub.tsv
/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/SRR6249787.sub.fastq   I_3_55  I_3_55.Lib1_C09_AGAAGTC
/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/SRR6249788.sub.fastq   I_3_66  I_3_66.Lib1_D06_GCCAACT
/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/SRR6249795.sub.fastq   PT_F    PT_F.Lib1_E09_TGAACAT
/mnt/f/GBS-run_enviroment/Reads2Map_tutorial/SRR6249808.sub.fastq   PT_M    PT_M.Lib2_E06_CGATGCG

**Comment by lmtani** [comment]
Hi! Could you send me the file generated by the command:

```sh
curl http://127.0.0.1:8000/api/workflows/v1/00461381-62e3-418c-885e-d1d0845acfc7/metadata > out.json
```

Pumbaa parses this json file and presents it in a nice table, but there are other fields in it that can help us understand what went wrong.

When calling cromwell directly it ends processing without any problem? I just ran the tutorial [described here](https://cristianetaniguti.github.io/Tutorials/Reads2Map/Setup_and_run_Reads2Map_workflows.html) on my Ubuntu and had no issues, it might be something related to WSL. With the json, I can investigate better.

**Comment by kmosi0** [comment]
When calling cromwell directly it will absorb in later steps, but generate some bam files. 
here is the file below. because the github do not support json format file ,so the change it to txt format.
[out.txt](https://github.com/Cristianetaniguti/Reads2Map/files/11997294/out.txt)

**Comment by kmosi0** [comment]
It seems input files doesn't be recognized.

**Comment by lmtani** [comment]
Cromwell raises this error:

> java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

I believe it's because of this config I made in the .cromwell/cromwell.config file provided by Pumbaa:

```sh
❯ cat ~/.cromwell/cromwell.conf
...
engine {
  filesystems {
    gcs {
      auth = "application-default"
    }
...
```

I'll check later today to see if that's the case.

**Comment by kmosi0** [comment]
is very well. I solve the problem ,after I delete the line in ~/.cromwell/cromwell.conf
```
 gcs {
      auth = "application-default"
    }
```
the workflow "EmpiricalSNPCalling_develop.wdl" is work finely. 
But an issue occurred when I try the  "EmpiricalSNPCalling_v1.4.1.wdl",with pair end fastq files some wrong in GATK and Stack Genotyping.
`❗You have 1 issue:
 - Workflow failed
 - Workflow failed
 - Job StacksGenotyping.RefMap:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
 - Workflow failed
 - Job GatkGenotyping.ImportGVCFs:1:1 exited with return code 2 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
 - Job GatkGenotyping.ImportGVCFs:0:1 exited with return code 2 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.`
[new_issue.txt](https://github.com/Cristianetaniguti/Reads2Map/files/12016511/new_issue.txt)
here is the err info below "find: ‘gvcfs/*.g.vcf.gz’: No such file or directory
Using GATK jar /usr/gitc/gatk4/gatk-package-4.1.8.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms520m -Xmx1000m -jar /usr/gitc/gatk4/gatk-package-4.1.8.0-local.jar GenomicsDBImport --batch-size 50 --reader-threads 5 --genomicsdb-workspace-path cohort_db -L Chr10 -V --consolidate
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell-executions/SNPCalling/f47b8bbd-87d0-4c82-b308-fb5a456f5706/call-GatkGenotyping/GatkGenotyping/c7597ffa-c0fd-4ce4-a356-a6822d1a7f27/call-ImportGVCFs/shard-0/tmp.7ca8e09c
09:41:44.576 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/gitc/gatk4/gatk-package-4.1.8.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jul 11, 2023 9:41:48 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
09:41:48.744 INFO  GenomicsDBImport - ------------------------------------------------------------
09:41:48.744 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.1.8.0
09:41:48.744 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
09:41:48.744 INFO  GenomicsDBImport - Executing as root@1fe11e43dde8 on Linux v5.10.16.3-microsoft-standard-WSL2 amd64
09:41:48.744 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_292-b10
09:41:48.744 INFO  GenomicsDBImport - Start Date/Time: July 11, 2023 9:41:44 AM GMT
09:41:48.744 INFO  GenomicsDBImport - ------------------------------------------------------------
09:41:48.744 INFO  GenomicsDBImport - ------------------------------------------------------------
09:41:48.744 INFO  GenomicsDBImport - HTSJDK Version: 2.22.0
09:41:48.745 INFO  GenomicsDBImport - Picard Version: 2.22.8
09:41:48.745 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
09:41:48.745 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
09:41:48.745 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
09:41:48.745 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
09:41:48.745 INFO  GenomicsDBImport - Deflater: IntelDeflater
09:41:48.745 INFO  GenomicsDBImport - Inflater: IntelInflater
09:41:48.745 INFO  GenomicsDBImport - GCS max retries/reopens: 20
09:41:48.745 INFO  GenomicsDBImport - Requester pays: disabled
09:41:48.745 INFO  GenomicsDBImport - Initializing engine
09:41:48.752 INFO  GenomicsDBImport - Shutting down engine
[July 11, 2023 9:41:48 AM GMT] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 0.07 minutes.
Runtime.totalMemory()=657457152
***********************************************************************

A USER ERROR has occurred: Failed to create reader from file:///cromwell-executions/SNPCalling/f47b8bbd-87d0-4c82-b308-fb5a456f5706/call-GatkGenotyping/GatkGenotyping/c7597ffa-c0fd-4ce4-a356-a6822d1a7f27/call-ImportGVCFs/shard-0/execution/--consolidate

***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace."
wish for your help. thanks !

**Comment by kmosi0** [comment]
There are  some err in BWA alignment, the bam file size less than 1k, but I don't know I to slove it . did you test the workflow with pair-end fastq files? I think it may be some thing wrong in it .  reply me plz.  lol
[BWA_stderr.txt](https://github.com/Cristianetaniguti/Reads2Map/files/12028900/BWA_stderr.txt)

**Comment by Cristianetaniguti** [comment]
Hello, 

Sorry, I needed to test by myself because I didn't remember which dataset I used before. But I made the modifications you need. Please, download the [new version of the workflows](https://github.com/Cristianetaniguti/Reads2Map/releases/tag/EmpiricalSNPCalling_v1.4.2). Here is one example of the JSON input data for you:

```
{
  "SNPCalling.chunk_size": 2,
  "SNPCalling.gatk_mchap": false,
  "SNPCalling.P1": "P1",
  "SNPCalling.pop_map": null,
  "SNPCalling.rm_dupli": false,
  "SNPCalling.samples_info": "tests/data/polyploid/fastq/pair_end/samples_info.txt",
  "SNPCalling.max_cores": 4,
  "SNPCalling.max_ram": 4000,
  "SNPCalling.pair_end": true,
  "SNPCalling.P2": "P2",
  "SNPCalling.ploidy": 4,
  "SNPCalling.run_tassel": false,
  "SNPCalling.references": {
    "ref_fasta": "tests/data/polyploid/RchinensisV1.0/Chr04_sub.fasta",
    "ref_dict": "tests/data/polyploid/RchinensisV1.0/Chr04_sub.dict",
    "ref_ann": "tests/data/polyploid/RchinensisV1.0/Chr04_sub.fasta.ann",
    "ref_sa": "tests/data/polyploid/RchinensisV1.0/Chr04_sub.fasta.sa",
    "ref_amb": "tests/data/polyploid/RchinensisV1.0/Chr04_sub.fasta.amb",
    "ref_pac": "tests/data/polyploid/RchinensisV1.0/Chr04_sub.fasta.pac",
    "ref_bwt": "tests/data/polyploid/RchinensisV1.0/Chr04_sub.fasta.bwt",
    "ref_fasta_index": "tests/data/polyploid/RchinensisV1.0/Chr04_sub.fasta.fai"
  },
  "SNPCalling.hardfilters": true,
  "SNPCalling.run_stacks": true,
  "SNPCalling.run_freebayes": false,
  "SNPCalling.run_gatk": true,
  "SNPCalling.replaceAD": false,
  "SNPCalling.n_chrom": 1
}
```

You can find the genome for this example data set [here](https://github.com/Cristianetaniguti/Reads2Map/tree/develop/tests/data/polyploid/RchinensisV1.0). And the sample files [here](https://github.com/Cristianetaniguti/Reads2Map/blob/develop/tests/data/polyploid/fastq/pair_end)

I updated the tutorial including this information. Please, set `gatk_mchap` to false by now, we are still testing this tool.

**Comment by kmosi0** [comment]
OK, the new workflow is worked，thanks
