### ISSUE TITLE
how to construct linkage map from pair end fastq files

### ISSUE THREAD

**Issue by kmosi0** [Cristianetaniguti/Reads2Map#85]
Hello
      I have pair-end fastq files， how can I do some adjust for running Reads2Map， thanks！

**Comment by Cristianetaniguti** [comment]
Hello! 
Sorry for the delay in answering, but the good news is that I did it for you in this new release! Please, check the new [tutorial](https://cristianetaniguti.github.io/Tutorials/Reads2Map/Setup_and_run_Reads2Map_workflows.html) and an [example of input data](https://github.com/Cristianetaniguti/Reads2Map/blob/main/tests/data/polyploid/fastq/pair_end/samples_info.txt) in case of pair-end reads.

**Comment by kmosi0** [comment]
This is so great, I will try it. Thank you so much!
